add_compile_definitions(PSTL_BENCH_USE_SYCL)
if(NOT DEFINED PSTL_BENCH_BACKEND_LABEL)
    set(PSTL_BENCH_BACKEND_LABEL "SYCL")
endif()
add_compile_definitions(PSTL_BENCH_BACKEND="${PSTL_BENCH_BACKEND_LABEL}")
# Detect SYCL compiler: acpp (AdaptiveCpp) vs icpx (Intel DPC++)
get_filename_component(CXX_COMPILER_NAME ${CMAKE_CXX_COMPILER} NAME)
if(CXX_COMPILER_NAME MATCHES "acpp")
    message(STATUS "SYCL backend: AdaptiveCpp (acpp) — skipping -fsycl flag")
else()
    message(STATUS "SYCL backend: Intel DPC++ (icpx) — adding -fsycl flag")
    add_compile_options(-fsycl)
    add_link_options(-fsycl)
endif()
